// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcq6fs4BJ5j4usFXWIXHu2Z6byTFMnjRc',
    appId: '1:4872948844:android:12ab614bda9615e776dc49',
    messagingSenderId: '4872948844',
    projectId: 'astrojournal-2b048',
    storageBucket: 'astrojournal-2b048.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbkfEGbuxThSneU3nvCOXTmhnwJ-z1STE',
    appId: '1:4872948844:ios:c96c4c8788617f0176dc49',
    messagingSenderId: '4872948844',
    projectId: 'astrojournal-2b048',
    storageBucket: 'astrojournal-2b048.appspot.com',
    iosClientId: '4872948844-094avoafug9u4gtrehnk2mlsqtse9h9s.apps.googleusercontent.com',
    iosBundleId: 'dev.dellini.astroJournal',
  );
}
